version: "3"

volumes:
  database:
  uploads:

networks:
  default:
    external:
      name: nginx-proxy

services:
  database:
    image: postgres:13.4-alpine
    container_name: hedgedoc-db
    env_file: ".env"
    volumes:
      - database:/var/lib/postgresql/data
    restart: always

  app:
    image: quay.io/hedgedoc/hedgedoc:1.9.0
    container_name: hedgedoc-app
    env_file: ".env"
    environment:
      - CMD_DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      - CMD_DOMAIN=${HOST_HEDGEDOC}
      - CMD_PROTOCOL_USESSL=true
      - VIRTUAL_HOST=${HOST_HEDGEDOC}
      - LETSENCRYPT_HOST=${HOST_HEDGEDOC}
      - LETSENCRYPT_EMAIL=${SSL_EMAIL}
    volumes:
      - uploads:/hedgedoc/public/uploads
    restart: always
    depends_on:
      - database
