version: "3"

volumes:
  database:
  uploads:

networks:
  default:
    external:
      name: nginx-proxy

services:
  database:
    image: postgres:13.4-alpine
    container_name: hedgedoc-db
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DBNAME}
    volumes:
      - database:/var/lib/postgresql/data
    restart: always

  app:
    image: quay.io/hedgedoc/hedgedoc:1.9.0
    container_name: hedgedoc-app
    environment:
      - CMD_DB_URL=postgres://${PG_USER}:${PG_PASSWORD}@database:5432/${PG_DBNAME}
      - CMD_DOMAIN=${CMD_DOMAIN}
      - CMD_PROTOCOL_USESSL=true
      - VIRTUAL_HOST=${HOST_HEDGEDOC}
      - LETSENCRYPT_HOST=${HOST_HEDGEDOC}
      - LETSENCRYPT_EMAIL=${SSL_EMAIL}
    volumes:
      - uploads:/hedgedoc/public/uploads
    ports:
      - "3090:3000"
    restart: always
    depends_on:
      - database
