version: "3"

volumes:
  database:
  uploads:

networks:
  default:
    external:
      name: nginx-proxy

services:
  database:
    image: postgres:13.4-alpine
    container_name: hedgedoc-db
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data
    restart: always

  app:
    image: quay.io/hedgedoc/hedgedoc:1.9.7
    container_name: hedgedoc-app
    env_file:
      - .env
    environment:
      - CMD_DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      - CMD_DOMAIN=laub.liebechaos.org
      - CMD_PROTOCOL_USESSL=true
    volumes:
      - uploads:/hedgedoc/public/uploads
    restart: always
    depends_on:
      - database
