version: '3'

volumes:
  db:
  html:

services:
  db:
    image: mariadb:10.5.8
    container_name: nextcloud-db
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${NEXTCLOUD_DB_NAME}
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - MYSQL_USER=${NEXTCLOUD_DB_USER}
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW

  redis:
    image: redis:6.0.9-alpine
    container_name: nextcloud-redis
    restart: always

  app:
    build: app
    container_name: nextcloud-app
    depends_on:
      - db
      - redis
    restart: always
    volumes:
      - html:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${NEXTCLOUD_DB_NAME}
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - MYSQL_USER=${NEXTCLOUD_DB_USER}
    ports:
      - 8080:5000
