version: '3'

networks:
  default:
    external:
      name: nginx-proxy

services:
  app:
    build: app
    container_name: coturn
    restart: always
    env_file: '.env'
    environment:
      - VIRTUAL_HOST=${HOST_COTURN}
      - LETSENCRYPT_HOST=${HOST_COTURN}
      - LETSENCRYPT_EMAIL=${SSL_EMAIL}
