version: '3'

volumes:
  db:
  data:

networks:
  default:
    external:
      name: nginx-proxy

services:
  db:
    image: postgres:12.2-alpine
    container_name: aquadoggo-db
    env_file:
      - .env
    volumes:
      - ./init-dbs.sh:/docker-entrypoint-initdb.d/init-dbs.sh
      - db:/var/lib/postgresql/data

  app:
    image: p2panda/aquadoggo:v0.1.0
    container_name: aquadoggo-app
    depends_on:
      - db
    volumes:
      - data:/home/rust/.local/share/aquadoggo
    restart: always
    environment:
      - VIRTUAL_PORT=2020
      - VIRTUAL_HOST=${HOST_AQUADOGGO}
      - RUST_LOG=info
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DATABASE}
      - LETSENCRYPT_HOST=${HOST_AQUADOGGO}
      - LETSENCRYPT_EMAIL=${SSL_EMAIL}
    expose:
      - 2020
